CREATE TABLE loan_applications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    station VARCHAR(255) NOT NULL,
    loaning_date DATE NOT NULL,
    refund_date DATE NOT NULL,
    location VARCHAR(255) NOT NULL,
    sub_location VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    village VARCHAR(255) NOT NULL,
    id_no VARCHAR(255) NOT NULL,
    marital_status VARCHAR(255) NOT NULL,
    phone_no VARCHAR(255) NOT NULL,
    occupation VARCHAR(255) NOT NULL,
    family VARCHAR(255) NOT NULL,
    loan_applied DECIMAL(10, 2) NOT NULL,
    loan_in_words VARCHAR(255) NOT NULL,
    one_week_pay DECIMAL(10, 2) NOT NULL,
    two_weeks_pay DECIMAL(10, 2) NOT NULL,
    securities VARCHAR(255) NOT NULL,
    securities_particulars DECIMAL(10, 2) NOT NULL,
    loan_purpose TEXT NOT NULL,
    guarantor_name VARCHAR(255) NOT NULL,
    guarantor_id VARCHAR(255) NOT NULL,
    guarantor_phone VARCHAR(255) NOT NULL,
    guarantor_sign VARCHAR(255) NOT NULL,
    deponent_name VARCHAR(255) NOT NULL,
    deponent_address VARCHAR(255) NOT NULL,
    deponent_id VARCHAR(255) NOT NULL,
    deponent_sign VARCHAR(255) NOT NULL,
    sworn_at VARCHAR(255) NOT NULL,
    sworn_date DATE NOT NULL,
    commissioner_oaths VARCHAR(255) NOT NULL
);